sources:
  - beagle-hack-day
  - Pods/Beagle/iOS/Sources/Beagle/CodeGeneration/SourceryProtocols.swift
templates:
  - Pods/Beagle/iOS/Sources/Beagle/CodeGeneration/Templates
output:
  beagle-hack-day/Generated
args:
  shouldNotImportBeagleUI: 0
